name: Generate Advent of Code Data for Widget
on: push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: Braweria/aoc-widget-data-generator@main
        with:
          year: 2015
          language: Go
          repo: Braweria/advent-of-code-2015-go
          directory: days
          extension: go
          # output: example/output.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: generating aoc data
